name: alkiria

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install --save-dev gh-pages

      - name: Build web version
        run: npx expo export --output-dir dist

      - name: Check if dist exists
        run: |
          if [ ! -d "dist" ]; then
            echo "Error: dist directory not found!"
            exit 1
          fi

      - name: Configure Git user
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.ALKIRIA_TOKEN }}" | base64 -d > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Deploy to GitHub Pages
        run: |
          git remote set-url origin git@github.com:alkoria/alkiria.git
          npx gh-pages -d dist